// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package runtime

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	reflect "reflect"
)

// GetGeneratedDeepCopyFuncs returns the generated funcs, since we aren't registering them.
func GetGeneratedDeepCopyFuncs() []conversion.GeneratedDeepCopyFunc {
	return []conversion.GeneratedDeepCopyFunc{
		{Fn: DeepCopyruntime_RawExtension, InType: reflect.TypeOf(&RawExtension{})},
		{Fn: DeepCopyruntime_TypeMeta, InType: reflect.TypeOf(&TypeMeta{})},
		{Fn: DeepCopyruntime_Unknown, InType: reflect.TypeOf(&Unknown{})},
	}
}

// DeepCopyruntime_RawExtension ...
func DeepCopyruntime_RawExtension(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*RawExtension)
		out := out.(*RawExtension)
		*out = *in
		if in.Raw != nil {
			in, out := &in.Raw, &out.Raw
			*out = make([]byte, len(*in))
			copy(*out, *in)
		}
		// in.Object is kind 'Interface'
		if in.Object != nil {
			newVal, err := c.DeepCopy(&in.Object)
			if err != nil {
				return err
			}
			out.Object = *newVal.(*Object)
		}
		return nil
	}
}

// DeepCopyruntime_TypeMeta ...
func DeepCopyruntime_TypeMeta(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*TypeMeta)
		out := out.(*TypeMeta)
		*out = *in
		return nil
	}
}

// DeepCopyruntime_Unknown ...
func DeepCopyruntime_Unknown(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*Unknown)
		out := out.(*Unknown)
		*out = *in
		if in.Raw != nil {
			in, out := &in.Raw, &out.Raw
			*out = make([]byte, len(*in))
			copy(*out, *in)
		}
		return nil
	}
}
